version: '2'

services:
  db:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: "user"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_INITDB_DATABASE: "mydb"

    ports:
      - "27017:27017"

  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/app"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db